use std::ops::Index;

#[derive(Clone, Debug)]
pub struct Rucksack {
    pub compartment_a: String,
    pub compartment_b: String,
}

impl Rucksack {
    fn new(input: String) -> Self {
        let aux = input.split_at(input.len() / 2);
        Rucksack {
            compartment_a: aux.0.to_owned(),
            compartment_b: aux.1.to_owned(),
        }
    }

    pub fn get_item_type_priority(&self, item_type: &String) -> i32 {
        let chars = String::from("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")
            .chars()
            .collect::<Vec<char>>();
        let item_priorities: Vec<i32> = (1..53).collect();

        return item_priorities[chars
            .iter()
            .position(|&x| String::from(x) == *item_type)
            .unwrap()];
    }

    pub fn get_item_type_in_both_compartiments(&self) -> String {
        let mut existing_chars = std::collections::HashMap::new();

        let mut repeated_item_type = 'a';

        for item_type in self.compartment_a.clone().chars() {
            existing_chars.insert(String::from(item_type), true);
        }

        for item_type in self.compartment_b.clone().chars() {
            if existing_chars.contains_key(&String::from(item_type)) {
                return String::from(item_type);
            }
        }

        return String::from(repeated_item_type);
    }

    pub fn get_repeated_item_type_priority(&self) -> i32 {
        self.get_item_type_priority(&self.get_item_type_in_both_compartiments())
    }
}

pub fn get_input() -> Vec<Rucksack> {
    let input = vec![
        "dtddvvhwttHJhwdhJPddhwJGppmGjgpQgTjQplQpTljwpg",
        "BfzSzRSVVMVNRMDDNBSNSnfBmbrglGQbmNpQggFjpgpbQlQb",
        "ZSBffLnVZdCCPJjhhL",
        "RGCZpWWWFlHQQbgvFssg",
        "jLnMzjnrnjjNjhrjdwbHscsVVgDVQPvPwh",
        "nfJnLMLzjJMtnjNnnBbZtBWBqqbTTTBRpT",
        "nddlhBtqTBqTVSlBtmCmVcRVmZggfWbcZc",
        "jDjvPrPSNPwrDNRWbbgWCjRRCcWm",
        "DzDwSpFrvrvFPQLzQnsqztBthTJnGJqlsJ",
        "gssGmzwgRgsNmTsqgDnDJnbDHHhhzFdDDh",
        "WQVFjMWrVQrVvVVjVctSSLSMZhnJZPBnbdnhbnHZZBDJBh",
        "VCtcccVQLrfvrSlGmfTfNgfmlFgm",
        "DsmfsBbNNZhDWsbmWmNbbPDHLFjcctjjGcnZGzncnctcGH",
        "SwVQJrjVwpgSVRpjpVRrlTMCFFCLCFFcHzzGMcHrtHHH",
        "ppVwTwSwpwvSlSlJTjVVbPhsvvBssWsNfsqWPvWs",
        "BJwqwJtqqDDDrGDnPFzPFfpphD",
        "TgZscCHQLSHgZcfMzpjFFjzsshfj",
        "LcNlTVQCCVLLZTLNvpRtpvBBvRJmNB",
        "bDBGQBBCTTNPGPPwPzcHfVHrDtLWLVrWVjjHWr",
        "gpssqqsqlMFfLZQWftjVpr",
        "lvqqFMRlFcQvbzCNCG",
        "fhhMDdPhWMJMWvhhSfwRSGlzFbSFNlzw",
        "LcqTCqcgZqjTggVjcwbFRwbDBTzbRGRwTS",
        "cHLpZgnCHpQsDdsmQp",
        "jwStJjJhtgJStpgwJMggQWqQTNTfNTWfbNNMCCNG",
        "zRZnFPRZPVncPGVFRlRmGHCTqfCCPCHHfLfbTQCbTq",
        "lnVmFZRZDnRVBFZcrZlhjpggvppthGhphpwprS",
        "lcttSptHHllQbMcsrltSQGpvNBzpgWBBBDDGWzvgLz",
        "PdjPVRFhFqFjRRCjzvRWnWLBLgbBBLzg",
        "hhCCFbPTmjPdhZjhPhZCmTjjMsrJSfHrcmHJrHHmlcJSsmft",
        "WhWnLZSSnSzQQhfLLNSfmDHrCFDDHtpjGGtTGQCG",
        "gJbJBcMVwJlRRdbwvwJBVtjdtHHTmptpHTCtTFrFCp",
        "JwwgvRMJlvJwgqgvqRMcnWWhLPzzsqfnZWnfWWnj",
        "zdwTSvzHMvVSzDCtZhtGmbTGhm",
        "lcBHfFjjgtsmDCgshD",
        "cJPBnqNFnLfHJFPqljclqJzQvSSVWvSnMwvSzSWWdMWM",
        "pNJMcZrsZDLDcbcccMpQffHqvgdwdFFmdmqwvqmgmzsw",
        "hhnWjTTStRCGSMgvvgvdqvdFjvVz",
        "hCTSWhPGttTCGBWMRlTCMSnPBDJpbDfDpNpbbNJfJDJbpJpN",
        "lbcQcSNFchhQNqHLLqhLqrMpqM",
        "WfsnsszPWfBBVpHdprrpdnGL",
        "WTzWfwjtTBzwwBDzmfSSQmmbFZcpQNcbZZbv",
        "PwSJSlmtPPgwgmHhPPvRvGHLRLQRBQGCQVGb",
        "rnsFDnnfGGRWQRnW",
        "dfTTfTFdfrfFFFzQFPJPSSlhqtllNPzgwS",
        "MMbTFZrcrGZMDqNStWScDtzS",
        "dvWmhQggQvCnfnqPqDnDjnfP",
        "lgvdvLClWCQlgdhlrMBBHpGlwbHHGH",
        "CQHgQpPdCQpsCpzRwSVRSzRZwZ",
        "JbNBbcbrJvbJnqVznwwTzrzz",
        "wNbfLvvfDNNBHPFLhddFsQss",
        "VVzqvwzpqvzqNVVHGNqjHpNfSQDWdWwJdPWrWccdQrWrrDdd",
        "nLcbtBRtBhcnWSJQlJSgll",
        "tFbLLLRRhMtsBMtRCRsLCMBVjjvHTNjHHjzcvFFppGHzTT",
        "QCPrPWNPlWjGGZqGmvdPGd",
        "JgpHpSfphhfpVmBSgnTvdtddGvZVdvddDv",
        "LhphBfHpSwSwfHcMgfpmBWWWbsNCjFWsljNbbjlLjb",
        "QJmQbRmdfmdSQRQZSJltTltNvTrtDtrlftDD",
        "wpZcHVwwMgBpWMVgWpHLphztDvvGvDPlnGvDLlNrDPnNPl",
        "McgWFWHHHzVpMgZQFqbjsdjqqRCq",
        "JPhLFfMJDLQnjNCvWWpdjjdM",
        "crSwnwVnwSRBcNBNjjWCdC",
        "GlbTGbsSzrtbmbfhnJQP",
        "fDLSWVDRHHfVWHgPcZlDlZbbQhBcZQbb",
        "jrmFmprTpFztmddjdjrpvBQlQZGhQbTsQbGcQbcbQs",
        "nvqdpmjFnwpLSWlfnVNnWl",
        "nZBRbBJzznNNCnJZwnBSCJMcpcTpcwhcqhmsmWMwFWLL",
        "jQfvjgtfvPlHHqWpvWThpWqWch",
        "VljjjgjQjrTDlDgrHtVCbnJZzNzNbnRNNJZrJR",
        "MQtJnttlMLlJQsNhQrVVrFVWRRbbVFdJDD",
        "vGjvzmjzgHqSjjSzmSGHTWbfDFWrbFzFfdDVrfRWDb",
        "qPRqvTSPggqGgHCmllnCNLtnhcnnsnnw",
        "zrlZsQMFrsgQFMMjMCbjVDCTCW",
        "NqHNRdBppcJJcTpdmRfHThpdDWDtvbWVtbLjWbttWqqCCbLt",
        "mhJpJHTJmBhcJhwhgwzsQwSSlzQQzGlZ",
        "TvsszlvnzRRVTqzVrqrjjZGPfQPFqPqG",
        "mcNhDNchppWmWSNhdSmSCQNjPFjrfGjrgPFCrgFPgPgrLf",
        "SDddWpdMWSwNDmMNwlJRQwJlsVRRvzlsHt",
        "DTtggjsFFFTlPJhvctBqBqSRmSMBSRnmnRcm",
        "fGfwZdrbHVLdbGdHHwwQGVwBBCMMfvCNRNSMMMSRBmmRCN",
        "dGZzGHGVVbvHvHwbzpGbHLrwFDDFTtsglhFspgJshslTDJjT",
        "CbzspssWwCPcvvplrfqfDCJrDqdllB",
        "LjttnjNTNGgQQJdBrffTwB",
        "nVtLSgggjFwtMczhvzpZbSZW",
        "HCzCHHvWthWFHhssWCVmnqZrnqVrmrmgnbrqmN",
        "wPPGBjQQGwGbSlSLwgnpnrBZnBBmnMNnMN",
        "jTTbJlJjPPLPGHHTthhhHcFWTT",
        "qRdvvPDrCpzPHzcdrrcRqtbJJgjhgtWjJgbWJtgCFb",
        "GTwGwNscLllGTZmGSTZGlSBMnhggjbgtgbtbsgWFFMhbMF",
        "ZSQBSmlmzcrdQRqz",
        "cSpTRphwwghRfgSScqPpnDqDCjDjJJJJDvDLCvvn",
        "BVmmQFQBQVNBVmsWlbQFGBBlCHTJznzHLHvvCnjjNLHJDLHD",
        "MFsZZMbBGblbQTmQsFsQMMfPcPcwSpwtStgPphZtctPc",
        "QZbbZBdjPBjbQQbZnSSltlfwWvlvwNtNjwFMMN",
        "DLVqTJqpSVtfsptwfWpv",
        "rcRRVVTSbPQBPrBZ",
        "tjSgSjLFSnVjDWRsQj",
        "lcdqhfFpqZGpZqznrVRWPrnWRVBsVG",
        "FHddNNNHwTHMHvvS",
        "qCSDSQlwBHNbgJrHnLJH",
        "GRpRpRfnmRWWVWgVrF",
        "jhdZjpnvGfTZZQPlCtqQQSsS",
        "FMZSGWWBrZjMBZMrBWMGjjZDnCRqpgPnbRwPbFnvvqFnDR",
        "QHcpfVVslfdVlQclcctqRgqgbsCwbCwPCCCPwD",
        "NLHfLhclmmhdfNNpfQMBmZWBrJMmZWBzMrjj",
        "pBMpRgBMQwzRthmzLC",
        "HPcJvrvDbjvrFDcvWrHfHfWHmdddtdTLztmtdtfllmNdNhNz",
        "DvPFDvnPJLngQsggMGGQ",
        "BbcFHvbhhDbbTSvZmwwgJPPlDlZldd",
        "prCrNLMNgWWJBdrJ",
        "fQMLCfLLtpqsNNMnnfBhcBSVGbhhhcqVbcjc",
        "ZchcZZjmmNpgmJtgmM",
        "RLrHllWrQZQGlBpbGFGFFM",
        "RQnLHrqPLnZHzqjfVPcvVTfCvPTC",
        "fMtwjfMwrbjfGrtrpPGrwpNNVNVqcbdVqHZTFNbcHSNL",
        "mgzvDnJmnJhFJHSTNqZLHncHLS",
        "vRzhzslJFhRffPPQMjGtGl",
        "VMMNjWppQVwzNWrZdrrtMCMZCtMT",
        "ngDScLcvPPgDPDGhGDPGSHVbHTHmZtTSrBHZbZBmBb",
        "LhlglLghnVlplswJjs",
        "bGJQZZTQQLJJbQZlTZLjCGQTsDhWFhmshhvjWVFVVrgtDsst",
        "NScqwHcwwnnzBwqPqqsmVNhgsDDVtsghrFFg",
        "pcrcwnpcffrcBzfbCRLpRLMMRlRLQl",
        "hzCzCzpRgCzzzCctNsNWNqsZqZhPqNPb",
        "TdBwmdrrrDmvwTvqNsSRssPlsWsq",
        "FDBRRHDMTmBfmrmngnpjGgVptMgLCp",
        "ZPLLnSPMFGvFZMSvHhDhqHfqvfqbDW",
        "GgcppCgBcrQBBgplrVddhDqqqfdHgWdfqb",
        "CcCjQszmGBQjrcCwCmCccPwPTPnMPTnMJSMMRZSPJL",
        "LcVVcqqSHRLzRnCfNnGzNW",
        "LZPPdljlCggMjgNM",
        "PTvwlPtwtlJvZTQvbcHppFLHVVTcFssF",
        "fpWzvzNgWJBVfBJzWzBVJNzWbZcbHhlbthjlrrPrjZZPHZhJ",
        "hRDmGCFDwQnStncrjnccHcMP",
        "GmmsGRmFTsFwSCsRQDsCSqqpfvfgzddWggvqdpfBWzVh",
        "wjRBFljJGDFwwlGGpBSjGDtwTVtTgHHHsHHsVTVzsHqq",
        "CPLNPdbWvbMWbcmvPNdLVqtsHqgCqHChZhhsVsHt",
        "PWcPfPvmvNQbbWdWpJjJBDptGnDFjftn",
        "mFFmJpDMmmnJFjWDVclsSpcflSsQwSsc",
        "HrjNNjHNfVwLNSSl",
        "tdZbhjHZHPbdCTvbbhhrGbbHMFmRMvnRRFmmvJMDmgJDJMnq",
        "szJZhshbsfZJjbttchPctdTnWnRWVWMMnBdLRpMnBz",
        "SrNwvDSwrCmnVRvjpWLBBn",
        "ggGmgNFrgSDwmNgrCmtPsZPsjQGsqPcsqqJP",
        "gjSWSjJSWrWzppzW",
        "MCMzHNGNqHfscsFtrtwscVcr",
        "qGHNGNHLCnLmTCHfMMmNTzzldzgJlJZZgJljgTdD",
        "QGTQtQzTmdTsGTLcdFTGzdtBBjtwvBBJDvDMHJgjJvww",
        "lPlqsZWnDJjZvZgV",
        "ShCfCRnWGFsRRRrF",
        "lwGtndCrrmGCwdmhzQrBzrHvLVggPgHv",
        "fjMjDZJqSDJfJqDNDjJffjZLHPHHFvVFzHBLgLFpFpBSgL",
        "MsTZWRNZfJZZqMGVGhhlhhccRnhC",
        "MMvncqvcHcSnsdzzgvdfQjpljpQVTdDQDRTRlVpQ",
        "wLCrNtBFFHHThRlH",
        "bPJtHmCWssqgGPvq",
        "LvTLsmDWvTWqTsmqjRTmjwgdwgnMHMMFgdtHmBmFVn",
        "rlSCJzCSfpGGlhznQdnwFhtHgBFwtV",
        "SGZJJSSrVfCbGJLjPsWbvjRsPTqR",
        "pNqVVDCMVMBpqJVdMNHrccGHrtNtTFFFrQ",
        "hwmllWbvvbnPvbSvtrFhhJzzHztcTztT",
        "WSnbnPbbbvlWlRvnsqqMgLRMjLgVLCJdRV",
        "GphVTGVMtQwtJmtCJP",
        "FRRsBBsFqRNZNNrgqBdRfCZvbmPgmQzJQPnmJbJmQPJPPmwj",
        "RNqsFrRfZZsZWvNqWRFvrBZvWhhCGVplhlWTlTpSCLpMhWMD",
        "RZRjgbZHjjhsSnRsZstDRStsTVpFhBqFphMqPPpTFQVMPFTM",
        "zrcGJwNNdwJrfNdJWvGdJzdTlTFlqTVPFTVFPPBpqNTbBP",
        "WwLdLGfrRLStCZbD",
        "mrmTqJWTvDDppTDb",
        "DGzBfCzNDzdMwnLlbn",
        "FVZPFZFFZPgjmWZsDtsq",
        "TpnFTnFRCgRgldMRnDnRcrcdbdPBHbtPqbVcccrH",
        "WNWLfQQmfhhSNwmrcbSVqPtbZDZcPb",
        "LQhwLQvQvNfJhJRDMGFRlCMDMD",
        "vLFTDmjVvLgnNHPphN",
        "lMClGCmsRdCnPzCccngCpz",
        "dlGZwRsRrRwswGsdSbbZSbVDrVBmDWWWFJrTrFvFTmqV",
        "SGsZRqGLWLLtZRHRRcLHGTlJjzgJpjzTpNTNJNWpTm",
        "MPMPvFFvFBrPPDPMQMPChjgpNpSNTmmmpNlTDljlTz",
        "vnhrvMvnhSRqqLqnfn",
        "mGFrlBmFQNQFljhqqqqbmHMsTPRbWWCsLMWRsb",
        "wnwtvpwVzDVpvzzwZppnctMLtMPWWCstTsWTsTLffRRW",
        "vwDJgZnvZJFqgLBFGqgl",
        "QdGltnWNWqTdqQWvWsMJcrTcFcrgshJRMs",
        "BzPLCDPzzzzCCLLfCBzfSDmLMrDJMglrcRbbhRsFhMrRJcsM",
        "fjSzwwHfSzPzfCVBHlpdjGnZqnZptqQWjGvG",
        "VbJZbgVzvzmhQpQWpQzhDp",
        "tHPPcGcFBlCctCGtGcBBNlDLMGfMLwWfwwqMLLJwQWwp",
        "dCHTPTPJdTBFPdrZjgsjrjnmdgms",
        "JJpBvJQBZVvcFqqnsWdWvjsn",
        "DCfbDbTtbgfCSHqqNdFMPhPDFnPPDWsPjM",
        "bTmzTNCTNmfqTgJQcpLrpZLzVlVL",
        "dtTLntTjzTftnmwnqGGQHNmm",
        "SWbShCPMBgBRRFSFtRZZmm",
        "DlJPCJCgPWhttzpvdjcpVl",
        "WdzsNvWMzNsMHWddWCVffqmSmScLPvLPgLgLPplrrPmL",
        "BtnzbnBhbwttwtZlmmlgcwSrLgmmpm",
        "bFhQtbGBTnjBBbjTtFBbVDzddDDfjdDDqNWVjWHj",
        "ppmtpgLLZLCbMQvQQThdtrvPhV",
        "BBlHBwHRjHqBzzbHHqjjQdDQTDhPQDvnQlrQDQvr",
        "HGjFzwHNczbzRFcGzHGFSJSpspsmpssMLLSZCppmfs",
        "MpGrMMMcTsHMVHcvbwwmmcRSmDmDmv",
        "zCNptqCBQQLCNLCzbfvSvbSzSDRDSmSv",
        "CNNqNgNQJNgQtCqLlllZdZhTrThsnHpVVssPTsGP",
        "jhSGcShDrLcLLFcw",
        "MVzQvQNZVLHvHPdhLW",
        "qzhhQlVbgqjmSjJDsgmR",
        "CFzSPCgcsVVzFgzSCsBJwjdwJtNllnwglJlp",
        "QrvbqWvvLbmvDMMmbdwFWpNNwwwwptjJWn",
        "RZRZZqvvvDbDHCRTGchHFSGG",
        "SszgPSPPVltDlqtz",
        "WfTdTBdQdFnWBBBhBhNjVJtpNsVlDDDHHJWp",
        "hQhrLFsBwdQPggbRgPwRMg",
        "frRppMMDMpDnJfprnZhrrhpzWgvvGCvvFzWFvzvVVWFGJB",
        "TcmLwTsccqwqbPwsdwqdTPSvBvzzztvggVvQCGWQCLBvCv",
        "sswNjscwmqjwSssjdZNMfHHlHhfrnrgnfR",
        "JpBJBdmdzZzzpngmbCnlqnNbNM",
        "MMTHGccLTLvwRMlRnnQnbblnRnSs",
        "vVGtvMcjLVGHfHDrPPWZppBpJpfZZZ",
        "FGJtlttPdPtGFldlPRGpJTVzSBSSggHgJjVmBMHjJm",
        "rhbvqrQLrWqrWLLfqbjjgNmVNSgzTmNgNS",
        "hsffZQqnqCfZzlPPGlRlcwDs",
        "HDDdZpcFwHFRFcZqDctpRDHpwTCVwjrBTQTBLBLBJJBjjQTJ",
        "ldlMzhlPshPbLrrVrQQCMQjB",
        "glzNfWlvbHqSdNNNcF",
        "jZCMtnZZHCZwBWMwCwtMmfPFfvHDvzHFLPmFDfvh",
        "RcrQdRRdGTzGvDGmfgjh",
        "TsQscdQsQNTNqQQpRrRVCCBMMJJWMMVNVjnNJM",
        "zVPWhVzLzWBWHZnlqBllqlpRbGNdffscGNdbDRnNSfcG",
        "MtvSFQQwMcpsGRNGFR",
        "vvTwJJSgmCSMmjVPPJWWhzllWLVV",
        "RjdfnJfmbVvVJVFQcs",
        "rZDZGBBZVvLZLHFW",
        "qPzTDPlVrjNgfCdmPd",
        "bcjmQPrnbmVmsLVrLrjmcHGRWlZHHRwHpZRHWWwH",
        "nFhqzFqJzDJfvfSFqFfGHWZZHGRJRWHZWdpWwZ",
        "hBCtDSSFCTqCCFzSnzMrLNmrMNPTNMQPMmNL",
        "qvNBSJVDJGGVSJbVDDVhDbbqPjpWpWzWrnpWvvWPMjnWnpWz",
        "mlTltwcwMWTPfNTN",
        "CtCwFmCgmcmlRFmFCtRCHgmDJsbBhVqsbBHVDbNHDHJqqb",
        "csBFBsLrBGBWcgLcBvRgpRhbwRwlbQwbwQgD",
        "DCqmDmtTRtRlhdlh",
        "qnCmTNPmmCnSSzmzNzGLzLccGDBzGrBLvvcW",
        "FjfBjHnHzPFwhvFFqh",
        "bjRpGsNsPqQvPclb",
        "NWGGWGrrZVZjsCLmDMMgzgrSnzSm",
        "MDgmmsNCmZMWmHCZLrvnLBBjPLVlPVbW",
        "zcJGQwJdFRnrBVzqzvPr",
        "hTQwhJwcfTFddFdGSfcRQQGFsggsgsHHnSmgsgsmgCnHNZpC",
        "BPfwzfsgsvfszvBRbQpttRVpJbJpVg",
        "LhTmHLbmbcFTFrWCbFqhFHLHVRpVtQpZVVDVprnDMJtJQnVZ",
        "TGWWbTFFGTqlHhqhSdNdNfNSldjjBfjv",
        "zCzpWTccHlWcPzMljMttbJfjmlfm",
        "DqqQVZZqVsqJnbbnmjbJJQ",
        "ZRmDZsSgVmGLsVqsLDFvrcccHrcTWCgWHBCHcCWp",
        "cvGlQMtQlPtQWWMlcGsrFwFdbgdbdGGDCDCwdd",
        "VChVZNBVjTTfhNTFgzrzrJgSdzgzwf",
        "THThZTqZRHZRqNVZNTVLjRCMmQsntQctMnsPmMmMcWtLMQ",
        "pNRHrbNlNnRLNpMMMTrcGcGTcccz",
        "ZttBmsJmZdjsvTTvvdBMjDhfMGWGDfDfcScjfD",
        "CmtTtwvtCsgllNHPPFbLpC",
        "NpQcvwwRHvdfRvQsNfBQNvfRhVmVMqsZMmMshjMMtWZtMmrm",
        "CGHbSSzFLSSHzTnbLnCWMrtWMtjnZMhZrqZtqW",
        "FzCPPzLbPgFJbHSPldNRpgNfvvccgvwf",
        "nSjpnnhNchMQZMSScnshshncJCGwHGClwmHPZlJPTVZCwHJf",
        "LvtzBTgLWgLPlPwHPLPJ",
        "dTBDqRqFzzhQFhshhNhM",
        "HjjdPsjnllHsbnnDnbTBzLBFBZLLpRFRcCHRFz",
        "wqqWwQhQQMCQffqqhtwMGhpZFRRZvzWzFvBvpvmcRvZm",
        "fGfghtNhthqJrQqMqMMSgDdbPjbssDbdSnjCdd",
        "cqPwJJnnffBFqSfJFnDDPVplLdglGgLVjzGLdVSzVt",
        "WHRTWNHsQTNbzsbCbTsvWrWtjlgVdLgLdvdgvmLjpGlgtm",
        "ZMQrTbNHZNsHHrQCZrNDFzhwnMJcfnDhJPPPFh",
        "LRCFbjNjbCZDmtmqmRRmLtFJBgWBBpvJMwBJvGjBBvMBgw",
        "TTrlfHzccVllZhdQgdGMJWvgWgBndwpG",
        "fVSshSVlsfslhsSHHSZtZZNmNFmtmbFCDF",
        "SPGCBPDMtbcbCtchSMccDTTrrrTFTrsrMTWHTHFVWF",
        "JmnzqVmmwwfpJpmdHRTRsdsTrFdrQp",
        "LqwLgzJgnjqLwgGcVbtjDGjcVbhv",
        "PQcMvrvMsvmdSPPVccmSJcSpGBWWWbBHfWWnfttJWnWJpJ",
        "wDzqhjzmqRzDRwqDzNDbWtjWBBBtGbtHpHnnBf",
        "zglRhDqqDZgRNmZQVCdcCPQvvdZv",
        "RpVjRgvFjGBNWtBWFDtt",
        "dcqQwlqMMsCLLfbgQmtD",
        "snlgzsggTzSTSJTr",
        "dLHhDdtlMngFcFsFLFzzsj",
        "vWRGGRVrrWvvGQQJBRsmQzmsqnffqcNfNcfz",
        "vSRVJBVBwTvWTnHphTgDgtMpDl",
        "bvvGnnJbfPmfdgJJSVtwwCpTScVfNpSC",
        "sjsZWDqBqqMRZsDjbWMVwtwNNcNtScRHpRRttp",
        "hzhDqqWDzZzDZzZLQPJPdPnPvlrbGdlnFQ",
        "PwWHTwzFvNHsNzmmMwzNWGQrCqCFjpZbpnGqrqnpbr",
        "gRVRgJRJlDLSJddDccQVrtZnCqjndnrZdnqnqpdq",
        "chhgSSJfQhRRcSSSSBLVfzmzHTNzMNsTNWHMMvMP",
        "lftqSpBSvhlDBDlhBSczQGmcFMcMVVFMmGFWsm",
        "rHLHTNdggsLLnwLHbTTgdrTMPPmMGWZGQQMzQVQFZQGM",
        "gbJnrHHjnbrgLrRrHpBJvSBDDsfJsDtstq",
        "dBTtFLTtVmpdLhMprSRSWMRSMR",
        "QvJvQbjbCgCQRBhzzRsNWNBC",
        "bjgGqQGbQnjGQgnQgbGgjJnDLHLdfPVtdDmLZdBFVVZttdTf",
    ];
    let mut rucksacks = vec![];

    for item in input {
        rucksacks.push(Rucksack::new(item.to_owned()));
    }

    return rucksacks;
}

pub fn get_answer() {
    let input = get_input();

    println!(
        "Total sum is: {:?}",
        input
            .iter()
            .map(|x| x.get_repeated_item_type_priority())
            .collect::<Vec<i32>>()
            .iter()
            .sum::<i32>()
    );
}
